### ISSUE TITLE
(credit mutuel) Monetico compatible

### ISSUE THREAD

**Issue by xorgxx** [KptiveStudio/KptivePaymentSipsBundle#12]
Hi i need to code payment system for Monetico (credit mutuel), my question it's still compatible ?

**Comment by youbs** [comment]
Hi!

Honestly I just don't know, I haven't used it in a live project for at least 2 years...
But I can point you towards a project that seem to be actively maintained (plus it's 100% PHP, whereas mine is a wrapper on C binaries): https://github.com/worldline/Sips-International-non-FR-PHPlibrary

Hope that helps

**Comment by xorgxx** [comment]
@youbs Thank's for your fast answer, i will look the library you give.
